### ISSUE TITLE
[Bug] Upgrade slots Dupe

### ISSUE THREAD

**Issue by AlienXtream** [Globox1997/ExtendedDrawersAddon#2]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.24

### Mod Version

1.0.1

### Describe the Issue

when using upgrades such as voiding and lock the items in the GUI are items that can be removed. when using a drawer access point or shift clicking the drawer with the item(s) they are not consumed (intended behavior for this mod). this means the versions in the GUI are duplicates that can be removed via GUI (and possibly other "smart" inventory interactions such as computer craft turtles)

### latest.log

N/A

**Comment by Globox1997** [comment]
[extendeddrawersaddon-1.0.2.zip](https://github.com/Globox1997/ExtendedDrawersAddon/files/13662229/extendeddrawersaddon-1.0.2.zip)
Please test this (unzip)

**Comment by AlienXtream** [comment]
crashes when opening (or trying to) the GUI
>Description: Rendering screen

>java.lang.NoSuchMethodError: 'void net.extendeddrawersaddon.screen.DrawerScreen.method_25420(net.minecraft.class_332)'
>	at net.extendeddrawersaddon.screen.DrawerScreen.method_25394(DrawerScreen.java:22)
>	at net.minecraft.class_437.method_47413(class_437.java:110)
>	at net.minecraft.class_757.method_3192(class_757.java:946)
>	at net.minecraft.class_310.method_1523(class_310.java:1275)
>	at net.minecraft.class_310.method_1514(class_310.java:856)
>	at net.minecraft.client.main.Main.main(Main.java:253)
>	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
>	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
>	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
>	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
>	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
>	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
>
full logs and crash 
\/

[crash-2023-12-14_17.04.28-client.txt](https://github.com/Globox1997/ExtendedDrawersAddon/files/13669359/crash-2023-12-14_17.04.28-client.txt)

[latest.log](https://github.com/Globox1997/ExtendedDrawersAddon/files/13669360/latest.log)

**Comment by Globox1997** [comment]
Please try with mc 1.20.1

**Comment by AlienXtream** [comment]
did... did really fail that hard at testing... to not even select the correct version... 😳
yeh. that doesn't crash (now that i used the correct version...). using the "access point" still dupes. individual drawers can't be shift clicked, letting you dupe the lava bucket and lock. im guessing you're going for "void and lock use up item" (if so, lock should not be used, void should be separate stackable item)? also, capacity upgrades dupe when taken out via GUI (as it the full on drop two. one in world, one on cursor) and cant be shift clicked onto drawers either

**Comment by lpjn** [comment]
I'm seeing this too. 

https://github.com/Globox1997/ExtendedDrawersAddon/assets/38690189/5d73fcbf-7a73-4d7d-a14b-9b086b2fd886

https://github.com/MattiDragon/ExtendedDrawers/issues/106 - More info

Please provide an update @Globox1997

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/ExtendedDrawersAddon/commit/cf29804fa5a6ddb33577194e772f06fa2ae744f4](https://github.com/Globox1997/ExtendedDrawersAddon/commit/cf29804fa5a6ddb33577194e772f06fa2ae744f4)
