### ISSUE TITLE
[Crash] with Extended Drawers 2.1.0

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/ExtendedDrawersAddon#4]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.25

### Mod Version

1.0.1

### Describe the Issue

Crash with newest update of base mod

### latest.log

https://gist.github.com/xR4YM0ND/b1b07102e6a420fe6f41c18dd801c761

**Comment by MattiDragon** [comment]
(I'm the dev of extended drawers). This is probably caused by me refactoring out shared code between compacting drawers and normal drawers into a shared superclass. Should probably just need a few tweaks to the mixins.

**Comment by Globox1997** [comment]
I think I updated it properly ;)

**Comment by FeedTheChunk** [comment]
Is there a resolution to this issue?  I have the same issue when running on a server.  The client runs fine but I get the same "Could not execute entrypoint stage 'main'" error message when loading on a server.

**Comment by Globox1997** [comment]
Fixed definitely with [https://github.com/Globox1997/ExtendedDrawersAddon/commit/cf29804fa5a6ddb33577194e772f06fa2ae744f4](https://github.com/Globox1997/ExtendedDrawersAddon/commit/cf29804fa5a6ddb33577194e772f06fa2ae744f4)
