### ISSUE TITLE
[Suggestion] Remvoe Model Gap Fix As A Required Dependency

### ISSUE THREAD

**Issue by tivvo** [Globox1997/ExtendedDrawersAddon#5]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

for starters, it's LITERALLY required on the server and has multiple issues when it comes to lag, especially when loading new chunks
i'm not even sure why its required besides for fixing models, unless the mod has an extreme issue when rendering items

**Comment by Globox1997** [comment]
Removed hard dependency with [https://github.com/Globox1997/ExtendedDrawersAddon/commit/65db5ca4b7704eb465c9c3ca5763d9a6483db100](https://github.com/Globox1997/ExtendedDrawersAddon/commit/65db5ca4b7704eb465c9c3ca5763d9a6483db100)

**Comment by swe3per** [comment]
Is it possible to modify the 1.20.1 version?
