### ISSUE TITLE
Crash when opening Drawer Upgrades Screen

### ISSUE THREAD

**Issue by Jack-Chronicle** [Globox1997/ExtendedDrawersAddon#6]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.11

### Mod Version

1.0.2

### Describe the Issue

When Shift+Right Clicking a Drawer to open the upgrade screen, the game crashes

### latest.log

[latest.log](https://github.com/user-attachments/files/15949527/latest.log)

### Do you use any other mods except the required ones?

Only required mods

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/ExtendedDrawersAddon/commit/3723ecf81da727e280021ac8b70df5a0838e17a5](https://github.com/Globox1997/ExtendedDrawersAddon/commit/3723ecf81da727e280021ac8b70df5a0838e17a5)

**Comment by Jack-Chronicle** [comment]
This update seems to only apply to the 1.21 version, could you update the 1.20.X version with it as well?

**Comment by Globox1997** [comment]
Since some 1.20 version Mojang changed their version scheming, so .X versions might all need custom work (basically time which is very limited)
I am open for a PR.
