### ISSUE TITLE
[Bug] ExtendedDrawersAddon disables shift-rightclick upgrading

### ISSUE THREAD

**Issue by PaterFrog** [Globox1997/ExtendedDrawersAddon#7]
### Minecraft Version

1.21.x

### Mod Loader Version

0.15.11

### Mod Version

1.0.2+1.20.1

### Describe the Issue

Enabling your mod disables the application of upgrades/locks/etc to slots. I have played around a little with the settings and tried turning things on or off. No change to the behavior. Shift-rightclick does nothing.
Once I disabled your mod and left only Extend Drawers enabled, I was able to apply the locks and upgrades just fine.

![image](https://github.com/Globox1997/ExtendedDrawersAddon/assets/46433636/95056ebe-a16f-49a9-967a-5815cb0bccd9)

### latest.log

[latest.log](https://github.com/user-attachments/files/16036924/latest.log)

### Do you use any other mods except the required ones?

loads, it's an entire customized modpack - Carry On may be interfering with your mod (it's the one that allows you to pick up blocks and carry them around via shift-rightclick.)

**Comment by Globox1997** [comment]
Enabled shift right click with [https://github.com/Globox1997/ExtendedDrawersAddon/commit/cf29804fa5a6ddb33577194e772f06fa2ae744f4](https://github.com/Globox1997/ExtendedDrawersAddon/commit/cf29804fa5a6ddb33577194e772f06fa2ae744f4)
