### ISSUE TITLE
REI + Latest Extended Drawers version causes outdated code execution; Crashing. 

### ISSUE THREAD

**Issue by Ynaught** [Globox1997/ExtendedDrawersAddon#8]
### Minecraft Version

1.21.x

### Mod Loader Version

Unsure. Going to guess 0.15.11, but I could be wrong.

### Mod Version

extendeddrawersaddon-1.0.3

### Describe the Issue

This a forwarding of [this](https://github.com/MattiDragon/ExtendedDrawers/issues/120) issue report I made in the main extended drawers github page. I am not sure which mod is responsible so I will leave them both here. I will add that upon removing just the addon, the crash didn't happen, but that much might be anecdotal. . . so I'm not confident enough to say conclusively that it was this mod at fault. Hence why I left the report in both places.

For further information see: https://github.com/MattiDragon/ExtendedDrawers/issues/120

### latest.log

See ExtendedDrawers issue #120 as linked above for this information. 

### Do you use any other mods except the required ones?

Yes.

**Comment by Ynaught** [comment]
Exact quote from the Extended Drawers dev:

> This crash is simply the addon being incompatible with the latest version of extended drawers. It just happens that rei caused the broken code in the addon to run.

So this addon apparently needs update to better support the latest version of the mod it's an addon to.

**Comment by Shadowdane** [comment]
I'm seeing the same crash here.    This addon is not compatible with the latest version of Extended Drawers.

**Comment by Globox1997** [comment]
Fixed it with [https://github.com/Globox1997/ExtendedDrawersAddon/commit/cf29804fa5a6ddb33577194e772f06fa2ae744f4](https://github.com/Globox1997/ExtendedDrawersAddon/commit/cf29804fa5a6ddb33577194e772f06fa2ae744f4)
